### ISSUE TITLE
Requerimiento de diagrama de flujo. 📐 (01/03?)

### ISSUE THREAD

**Issue by JohanMSR** [JohanMSR/Proyecto-Brazo-robotico-Universidad-#3]
### **Tareas Propuestas**

**Creación del Diagrama de Flujo**

> - Crear un diagrama de flujo que represente los pasos y decisiones dentro de “Funcion (Testing Motors)”. Utilizar herramientas como Draw.io.

> - Incluir etiquetas claras para cada nodo y flecha.

> - Asegurarse de que el diagrama sea fácil de seguir y comprenda.

**Creación de una Rama para el Diagrama**

> - Crear una nueva rama llamada “diagrama-exampleFunction” a partir de la rama “dev”.

> - Agregar el diagrama de flujo al directorio correspondiente en esta rama.

**Actualización del README**

> - Modificar el archivo README para incluir una breve descripción del diagrama y su ubicación en el repositorio.

**Revisión y Merge**

> - Solicitar a un compañero de equipo que revise el diagrama.

> - Una vez aprobado, fusionar la rama “diagrama-exampleFunction” con la rama “dev”.

**Beneficios**

> - Mayor comprensión de “exampleFunction” para todo el equipo.

> - Documentación visual que facilita futuras modificaciones y correcciones.

### **Requerimientos del Diagrama (Funcion probando motores)**

- [x] Crear una estructura iterativa y repetida que dependa de la cantidad de motores.

- [x] Aplicar una validacion de capacidad donde se lleve al motor testeado en un iteracion desde el minimo hasta el maximo de su potencia:

- [x] Crear un metodo de escape y reporte en caso de que los test unitarios fallen

```C
int validTest(int motor_1, bool log_valid_min,  bool log_valid_max){
    if (log_valid_min){
        return 1;
    }
    else{
        return 0;
    };
    if (log_valid_max){
        return 1;
    }
    else{
        return 0;
    }
   /*...*/
}
```
_Nota (Johan): Solo crear un diagrama usando Draw.io que itere todos los motores uno por uno (secuencial), pruebe el maximo de capacidad de cada uno y genere un reporte de que test unitarios fallaron por return id. No olvides crear tu rama y subir el archivo alli, cuando hagas tu pull request pide el review de algun miembro del repo_

_Responsable_
@Hedaor

**Comment by Hedaor** [comment]
Vale, entendido

**Comment by Hedaor** [comment]
@JohanMSR, una duda,una vez que termine el diagrama de flujo sobre el codigo del issue, lo mando a la carpeta de "Diagramas de flujo" con otro nombre o directamente reemplazo el archivo que esta ahi?
